export const AMENITIES_OPTIONS = [
  { value: 'Breakfast included', label: 'breakfastIncluded' },
  { value: 'Free WiFi', label: 'freeWifi' },
  { value: 'Parking', label: 'parking' },
  { value: 'Free airport shuttle', label: 'freeAirportShuttle' },
  {
    value: 'All-inclusive plan available',
    label: 'allInclusivePlanAvailable',
  },
  { value: 'Hot tub', label: 'hotTub' },
  { value: 'Kitchen', label: 'kitchen' },
  { value: 'Ocean view', label: 'oceanView' },
  { value: 'Air conditioned', label: 'airConditioned' },
  { value: 'Gym', label: 'gym' },
  { value: 'Pool', label: 'pool' },
  { value: 'Washer and dryer', label: 'washerAndDryer' },
  { value: 'Restaurant', label: 'restaurant' },
  { value: 'Pet friendly', label: 'petFriendly' },
  { value: 'Spa', label: 'spa' },
  { value: 'Casino', label: 'casino' },
];
