import { Flight } from './types/response/SearchResponse';

export const flightsListMock: Flight[] = [
  {
    legId: '1_1',
    segments: {
      collection: [
        {
          segmentCode: 'MIA_ATL_DL_1327',
          departureAirportName: 'Miami (MIA)',
          departureAirport: 'MIA',
          departureDateTime: '2023-04-20T08:20:00',
          departureTerminal: null,
          arrivalAirportName: 'Atlanta ��� Hartsfield Atlanta (ATL)',
          arrivalAirport: 'ATL',
          arrivalDateTime: '2023-04-20T10:13:00',
          arrivalTerminal: 'S',
          flightDuration: 0,
          layoverToNextSegmentsInMinutes: 47,
          aircraftType: '757',
          operatingCarrier: 'DL',
          operatingCarrierName: null,
          operatingFlightNumber: '1327',
          marketingCarrier: 'DL',
          marketingCarrierName: 'Delta',
          marketingFlightNumber: '1327',
        },
        {
          segmentCode: 'ATL_DAL_DL_1318',
          departureAirportName: 'Atlanta ��� Hartsfield Atlanta (ATL)',
          departureAirport: 'ATL',
          departureDateTime: '2023-04-20T11:00:00',
          departureTerminal: 'S',
          arrivalAirportName: 'Dallas Love Field (DAL)',
          arrivalAirport: 'DAL',
          arrivalDateTime: '2023-04-20T00:14:00',
          arrivalTerminal: '1',
          flightDuration: 0,
          layoverToNextSegmentsInMinutes: 0,
          aircraftType: '319',
          operatingCarrier: 'DL',
          operatingCarrierName: null,
          operatingFlightNumber: '1318',
          marketingCarrier: 'DL',
          marketingCarrierName: 'Delta',
          marketingFlightNumber: '1318',
        },
      ],
      legType: 'CONNECTING',
      totalFlightTimeInMinutes: null,
      fareAndCabinName: null,
      fareType: null,
    },
    offers: [],
  },
  {
    legId: '1_1',
    segments: {
      collection: [
        {
          segmentCode: 'MIA_ATL_DL_1327',
          departureAirportName: 'Miami (MIA)',
          departureAirport: 'MIA',
          departureDateTime: '2023-04-20T08:20:00',
          departureTerminal: null,
          arrivalAirportName: 'Atlanta ��� Hartsfield Atlanta (ATL)',
          arrivalAirport: 'ATL',
          arrivalDateTime: '2023-04-20T10:13:00',
          arrivalTerminal: 'S',
          flightDuration: 0,
          layoverToNextSegmentsInMinutes: 47,
          aircraftType: '757',
          operatingCarrier: 'DL',
          operatingCarrierName: null,
          operatingFlightNumber: '1327',
          marketingCarrier: 'DL',
          marketingCarrierName: 'Delta',
          marketingFlightNumber: '1327',
        },
        {
          segmentCode: 'ATL_DAL_DL_1318',
          departureAirportName: 'Atlanta ��� Hartsfield Atlanta (ATL)',
          departureAirport: 'ATL',
          departureDateTime: '2023-04-20T11:00:00',
          departureTerminal: 'S',
          arrivalAirportName: 'Dallas Love Field (DAL)',
          arrivalAirport: 'DAL',
          arrivalDateTime: '2023-04-20T00:14:00',
          arrivalTerminal: '1',
          flightDuration: 0,
          layoverToNextSegmentsInMinutes: 0,
          aircraftType: '319',
          operatingCarrier: 'DL',
          operatingCarrierName: null,
          operatingFlightNumber: '1318',
          marketingCarrier: 'DL',
          marketingCarrierName: 'Delta',
          marketingFlightNumber: '1318',
        },
      ],
      legType: 'CONNECTING',
      totalFlightTimeInMinutes: null,
      fareAndCabinName: null,
      fareType: null,
    },
    offers: [],
  },
];
