timeout: 3600s

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'docker build -t gcr.io/$PROJECT_ID/sn-web-v2-${_ENV}:$BUILD_ID . -f docker/Dockerfile-${_ENV} --build-arg NEXT_PUBLIC_ADMIN_ENDPOINT_URL=${_NEXT_PUBLIC_ADMIN_ENDPOINT_URL} --build-arg NEXT_PUBLIC_ADMIN_TOKEN=${_NEXT_PUBLIC_ADMIN_TOKEN} --build-arg NEXT_ENCRYPT_KEY=${_NEXT_ENCRYPT_KEY}',
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sn-web-v2-${_ENV}:$BUILD_ID']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sn-web-v2-${_ENV}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sn-web-v2-${_ENV}:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port=80'
images:
  - 'gcr.io/$PROJECT_ID/sn-web-v2-${_ENV}:$BUILD_ID'
