timeout: 3600s

steps:
  # Build the container image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >-
        docker build -t gcr.io/$PROJECT_ID/sn-web-v2-${_ENV}:$BUILD_ID . -f gcp.Dockerfile 
        --build-arg NEXT_PUBLIC_ADMIN_ENDPOINT_URL=${_NEXT_PUBLIC_ADMIN_ENDPOINT_URL} 
        --build-arg NEXT_PUBLIC_ADMIN_TOKEN=${_NEXT_PUBLIC_ADMIN_TOKEN} 
        --build-arg NEXT_ENCRYPT_KEY=${_NEXT_ENCRYPT_KEY}
        --build-arg NEXT_PUBLIC_GOOGLE_MAP_KEY=${_NEXT_PUBLIC_GOOGLE_MAP_KEY}
        --build-arg NEXT_PUBLIC_PURCHASE_MODE=${_NEXT_PUBLIC_PURCHASE_MODE}
        --build-arg NEXT_PUBLIC_KOUNT_CLIENT=${_NEXT_PUBLIC_KOUNT_CLIENT}
        --build-arg NEXT_PUBLIC_KOUNT_ENVIRONMENT=${_NEXT_PUBLIC_KOUNT_ENVIRONMENT}
    entrypoint: bash
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sn-web-v2-${_ENV}:$BUILD_ID']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sn-web-v2-${_ENV}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sn-web-v2-${_ENV}:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port=80'
      - '--update-env-vars=NEXT_PUBLIC_GOOGLE_MAP_KEY=${_NEXT_PUBLIC_GOOGLE_MAP_KEY}'
      - '--update-env-vars=NEXT_ENCRYPT_KEY=${_NEXT_ENCRYPT_KEY}'
      - '--update-env-vars=X_API_KEY=${_X_API_KEY}'
      - '--update-env-vars=API_URL=${_API_URL}'
images:
  - 'gcr.io/$PROJECT_ID/sn-web-v2-${_ENV}:$BUILD_ID'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _ENV: dev
  _NEXT_PUBLIC_ADMIN_ENDPOINT_URL: 'https://dev-admin.simplenight.com/client'
  _NEXT_PUBLIC_ADMIN_TOKEN: ''
  _NEXT_ENCRYPT_KEY: ''
  _NEXT_PUBLIC_GOOGLE_MAP_KEY: ''
  _NEXT_PUBLIC_PURCHASE_MODE: 'single'
  _NEXT_PUBLIC_KOUNT_CLIENT: '100982'
  _NEXT_PUBLIC_KOUNT_ENVIRONMENT: 'TEST'
  _X_API_KEY: ''
  _API_URL: 'https://dev-api.simplenight.com/v2'

