timeout: 3600s

steps:
  # Build the container image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >-
        docker build -t gcr.io/$PROJECT_ID/sn-bog-v2-${_ENV}:$BUILD_ID . -f docker/gcp.Dockerfile 
        --build-arg NEXT_PUBLIC_ADMIN_ENDPOINT_URL=${_NEXT_PUBLIC_ADMIN_ENDPOINT_URL} 
        --build-arg NEXT_PUBLIC_ADMIN_TOKEN=${_NEXT_PUBLIC_ADMIN_TOKEN}
        --build-arg NEXT_PUBLIC_AUTH_API_URL_V1=${_NEXT_PUBLIC_AUTH_API_URL_V1}
        --build-arg NEXT_ENCRYPT_KEY=$$NEXT_ENCRYPT_KEY
        --build-arg NEXT_PUBLIC_GOOGLE_MAP_KEY=$$NEXT_PUBLIC_GOOGLE_MAP_KEY
        --build-arg NEXT_PUBLIC_PURCHASE_MODE=${_NEXT_PUBLIC_PURCHASE_MODE}
        --build-arg NEXT_PUBLIC_KOUNT_CLIENT=${_NEXT_PUBLIC_KOUNT_CLIENT}
        --build-arg NEXT_PUBLIC_KOUNT_ENVIRONMENT=${_NEXT_PUBLIC_KOUNT_ENVIRONMENT}
        --build-arg NEXT_PUBLIC_FLIGHTS_MS=${_NEXT_PUBLIC_FLIGHTS_MS}
        --build-arg SN_NODE_ENV=${_SN_NODE_ENV}
        --build-arg GA4_TRACKING_ID=$$GA4_TRACKING_ID
        --build-arg VERSION=$REF_NAME-$SHORT_SHA
    entrypoint: bash
    secretEnv: ['GA4_TRACKING_ID', 'NEXT_ENCRYPT_KEY', 'NEXT_PUBLIC_GOOGLE_MAP_KEY']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sn-bog-v2-${_ENV}:$BUILD_ID']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sn-bog-v2-${_ENV}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sn-bog-v2-${_ENV}:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port=80'
      - '--update-env-vars=API_URL=${_API_URL}'
      - '--update-env-vars=NEXT_PUBLIC_FLIGHTS_MS=${_NEXT_PUBLIC_FLIGHTS_MS}'
      - '--update-env-vars=NEXT_PUBLIC_AUTH_API_URL_V1=${_NEXT_PUBLIC_AUTH_API_URL_V1}'
      - '--update-secrets=GA4_TRACKING_ID=GA4_TRACKING_ID:latest'
      - '--update-secrets=NEXT_PUBLIC_GOOGLE_MAP_KEY=NEXT_PUBLIC_GOOGLE_MAP_KEY:latest'
      - '--update-secrets=NEXT_ENCRYPT_KEY=NEXT_ENCRYPT_KEY:latest'
      # - '--update-secrets=X_API_KEY=X_API_KEY:latest'
images:
  - 'gcr.io/$PROJECT_ID/sn-bog-v2-${_ENV}:$BUILD_ID'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _ENV: dev
  _NEXT_PUBLIC_ADMIN_ENDPOINT_URL: 'https://dev-admin.simplenight.com/client'
  _NEXT_PUBLIC_ADMIN_TOKEN: ''
  _NEXT_PUBLIC_AUTH_API_URL_V1: 'https://dev-api.auth.simplenight.com/v1'
  _NEXT_PUBLIC_PURCHASE_MODE: 'single'
  _NEXT_PUBLIC_KOUNT_CLIENT: '100982'
  _NEXT_PUBLIC_KOUNT_ENVIRONMENT: 'TEST'
  _NEXT_PUBLIC_FLIGHTS_MS: 'https://dev-ms.simplenight.com'
  _SN_NODE_ENV: development
  _API_URL: 'https://dev-api.simplenight.com/v2'
availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_NUMBER/secrets/GA4_TRACKING_ID/versions/latest'
    env: 'GA4_TRACKING_ID'
  - versionName: 'projects/$PROJECT_NUMBER/secrets/NEXT_ENCRYPT_KEY/versions/latest'
    env: 'NEXT_ENCRYPT_KEY'
  - versionName: 'projects/$PROJECT_NUMBER/secrets/NEXT_PUBLIC_GOOGLE_MAP_KEY/versions/latest'
    env: 'NEXT_PUBLIC_GOOGLE_MAP_KEY'
