export const SET_BRAND_CONFIG = 'SET_BRAND_CONFIG';
export const SET_INTL_MESSAGES = 'SET_INTL_MESSAGES';
export const SET_LOCALE = 'SET_LOCALE';
export const SET_BRAND_COLOR = 'SET_BRAND_COLOR';
export const SET_IS_MAPS_LOADED = 'SET_IS_MAPS_LOADED';
export const SET_HOME_PAGE_SCROLL_HANDLER = 'SET_HOME_PAGE_SCROLL_HANDLER';
