import { Hotel } from './types/response/SearchResponse';

export default [
  {
    id: '704f71db:160156',
    name: 'Homewood Suites by Hilton Edgewater-NYC Area',
    description:
      "The following services and amenities are available, but with **reduced service**: Complimentary Evening Social, Fitness Center, Breakfast.The Homewood Suites by Hilton Edgewater-NYC Area, NJ hotel overlooks Manhattan from the western banks of the Hudson River in New Jersey. The convenient location of Homewood Suites by Hilton offers you easy access to all of the Tri-State area's corporate and industrial parks, popular tourist sites and attractions. \n\nThe Homewood Suites by Hilton in Edgewater, New Jersey features 122 spacious studio (king) suites and one-bedroom suites (with a king bed or two queen beds). The EMPIRE Suites boast a Manhattan skyline view and a whirlpool tub overlooking the master bedroom. Our suites will make guests feel right at home and pampered with a fully equipped kitchen including a full-size refrigerator, range top, microwave, dishwasher, and coffeemaker. Each suite has a sofa bed in the living area. Large flat-screen TVs, two-line telephones, iron with ironing board and hairdryers are just a few of the amenities found at our Edgewater, New Jersey Homewood Suites by Hilton hotel.",
    thumbnail:
      'http://photos.hotelbeds.com/giata/16/160156/160156a_hb_f_001.jpg',
    rooms: [
      {
        code: 'SUI.KG',
        room_type: 'SUI',
        description: 'SUITE KING SIZE BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3456.56,
          str: '$3,456.56',
          currency: 'USD',
        },
      },
      {
        code: 'SUI.CV-KG',
        room_type: 'SUI',
        description: 'SUITE CITY VIEW KING BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3604.24,
          str: '$3,604.24',
          currency: 'USD',
        },
      },
      {
        code: 'SUI.KG-3',
        room_type: 'SUI',
        description: 'SUITE KING SIZE BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3308.8,
          str: '$3,308.80',
          currency: 'USD',
        },
      },
    ],
    amount_min: {
      amount: 3308.8,
      str: '$3,308.80',
      currency: 'USD',
    },
    relative_position: {
      distance: 5.9816,
      distance_unit: 'mi',
      near_to: [
        {
          location_type: 'example',
          location_code: '123',
          location_name: 'Example Location',
          distance: '0',
        },
      ],
      distance_to_city_centre: 0.0,
      distance_to_nearest_airport: 0.0,
    },
    address: {
      coordinates: {
        latitude: 40.8065189832902,
        longitude: -73.9901393651826,
        radius: 15,
        unit: 'mi',
      },
      country_code: 'US',
      country: 'United States',
      state: 'NEW JERSEY',
      city: 'Edgewater',
      zone: 'Edgewater',
      district: '',
      address1: '10 The Promenade',
      address2: '',
      postal_code: '',
    },
    type: 'Hotel',
    star_rating: '3',
    web: 'https://www.hilton.com/en/hotels/ewrewhw-homewood-suites-edgewater-nyc-area/',
    email: 'EWREW_Homewood@hilton.com',
    phones: [
      {
        phone_number: '+180022554663',
        phone_type: 'PHONEBOOKING',
      },
    ],
    checkin_time: '14:00:00',
    checkout_time: '10:00:00',
    facilities: [
      'Minor - AvaniSHIELD',
      'Rosen - Total Commitment',
      'Morocco - Tourisme au Maroc post Covid-19',
      'RIU - Covid-19 Health Protocol',
      'Table tennis',
      'Morocco - Tourisme au Maroc post Covid-19',
      'Pedal boating',
      'Extra beds on demand',
      'Breakfast a la carte',
      'Fitness',
      'Cycling / mountain biking',
      'Blue Diamond Resorts - Enhanced Health, Safety & Cleanliness Protocols',
      'Table tennis',
      'Golf',
      'Minimum check-in age',
      'Pedal boating',
      'Wi-fi',
      'Skiing',
      'Squash',
      'Aerobics',
      'Launderette',
      'Multilingual staff',
      'Golf practice facility',
      'Bellboy service',
      'RIU - Covid-19 Health Protocol',
      'NH - Feel safe at NH',
      'Colombia - Check in certificado, COVID-19 bioseguro',
      'Minor - AvaniSHIELD',
      'WTTC - Safe Travels Stamp',
      'Newspapers',
      'Luggage room',
      'Clothes dryer',
      'Diving',
      'Smoking area',
      'Catamaran sailing',
      'Waterskiing',
      'Online check-in',
      'Spa centre',
      'Business centre',
      'Turkish bath (hamam)',
      'WaterSlides',
      'TV lounge',
      'Sauna',
      'Surfing',
      'Hairdressing salon',
      'Mauritian Standard on Sustainable Tourism',
      'Colombia - Check in certificado, COVID-19 bioseguro',
      'Non-smoking establishment',
      'Fitness',
      'Tennis',
      'Hilton - CleanStay',
    ],
    amenities: [],
    chain: {
      chain_code: '',
      chain_name: '',
    },
    supplier_prefix: '704f71db',
    supplier_id: '160156',
  },
  {
    id: '704f71db:160156',
    name: 'Homewood Suites by Hilton Edgewater-NYC Area',
    description:
      "The following services and amenities are available, but with **reduced service**: Complimentary Evening Social, Fitness Center, Breakfast.The Homewood Suites by Hilton Edgewater-NYC Area, NJ hotel overlooks Manhattan from the western banks of the Hudson River in New Jersey. The convenient location of Homewood Suites by Hilton offers you easy access to all of the Tri-State area's corporate and industrial parks, popular tourist sites and attractions. \n\nThe Homewood Suites by Hilton in Edgewater, New Jersey features 122 spacious studio (king) suites and one-bedroom suites (with a king bed or two queen beds). The EMPIRE Suites boast a Manhattan skyline view and a whirlpool tub overlooking the master bedroom. Our suites will make guests feel right at home and pampered with a fully equipped kitchen including a full-size refrigerator, range top, microwave, dishwasher, and coffeemaker. Each suite has a sofa bed in the living area. Large flat-screen TVs, two-line telephones, iron with ironing board and hairdryers are just a few of the amenities found at our Edgewater, New Jersey Homewood Suites by Hilton hotel.",
    thumbnail:
      'http://photos.hotelbeds.com/giata/16/160156/160156a_hb_f_001.jpg',
    rooms: [
      {
        code: 'SUI.KG',
        room_type: 'SUI',
        description: 'SUITE KING SIZE BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3456.56,
          str: '$3,456.56',
          currency: 'USD',
        },
      },
      {
        code: 'SUI.CV-KG',
        room_type: 'SUI',
        description: 'SUITE CITY VIEW KING BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3604.24,
          str: '$3,604.24',
          currency: 'USD',
        },
      },
      {
        code: 'SUI.KG-3',
        room_type: 'SUI',
        description: 'SUITE KING SIZE BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3308.8,
          str: '$3,308.80',
          currency: 'USD',
        },
      },
    ],
    amount_min: {
      amount: 3308.8,
      str: '$3,308.80',
      currency: 'USD',
    },
    relative_position: {
      distance: 5.9816,
      distance_unit: 'mi',
      near_to: [
        {
          location_type: 'example',
          location_code: '123',
          location_name: 'Example Location',
          distance: '0',
        },
      ],
      distance_to_city_centre: 0.0,
      distance_to_nearest_airport: 0.0,
    },
    address: {
      coordinates: {
        latitude: 40.8065189832902,
        longitude: -73.9901393651826,
        radius: 15,
        unit: 'mi',
      },
      country_code: 'US',
      country: 'United States',
      state: 'NEW JERSEY',
      city: 'Edgewater',
      zone: 'Edgewater',
      district: '',
      address1: '10 The Promenade',
      address2: '',
      postal_code: '',
    },
    type: 'Hotel',
    star_rating: '3',
    web: 'https://www.hilton.com/en/hotels/ewrewhw-homewood-suites-edgewater-nyc-area/',
    email: 'EWREW_Homewood@hilton.com',
    phones: [
      {
        phone_number: '+180022554663',
        phone_type: 'PHONEBOOKING',
      },
    ],
    checkin_time: '14:00:00',
    checkout_time: '10:00:00',
    facilities: [
      'Minor - AvaniSHIELD',
      'Rosen - Total Commitment',
      'Morocco - Tourisme au Maroc post Covid-19',
      'RIU - Covid-19 Health Protocol',
      'Table tennis',
      'Morocco - Tourisme au Maroc post Covid-19',
      'Pedal boating',
      'Extra beds on demand',
      'Breakfast a la carte',
      'Fitness',
      'Cycling / mountain biking',
      'Blue Diamond Resorts - Enhanced Health, Safety & Cleanliness Protocols',
      'Table tennis',
      'Golf',
      'Minimum check-in age',
      'Pedal boating',
      'Wi-fi',
      'Skiing',
      'Squash',
      'Aerobics',
      'Launderette',
      'Multilingual staff',
      'Golf practice facility',
      'Bellboy service',
      'RIU - Covid-19 Health Protocol',
      'NH - Feel safe at NH',
      'Colombia - Check in certificado, COVID-19 bioseguro',
      'Minor - AvaniSHIELD',
      'WTTC - Safe Travels Stamp',
      'Newspapers',
      'Luggage room',
      'Clothes dryer',
      'Diving',
      'Smoking area',
      'Catamaran sailing',
      'Waterskiing',
      'Online check-in',
      'Spa centre',
      'Business centre',
      'Turkish bath (hamam)',
      'WaterSlides',
      'TV lounge',
      'Sauna',
      'Surfing',
      'Hairdressing salon',
      'Mauritian Standard on Sustainable Tourism',
      'Colombia - Check in certificado, COVID-19 bioseguro',
      'Non-smoking establishment',
      'Fitness',
      'Tennis',
      'Hilton - CleanStay',
    ],
    amenities: [],
    chain: {
      chain_code: '',
      chain_name: '',
    },
    supplier_prefix: '704f71db',
    supplier_id: '160156',
  },
  {
    id: '704f71db:160156',
    name: 'Homewood Suites by Hilton Edgewater-NYC Area',
    description:
      "The following services and amenities are available, but with **reduced service**: Complimentary Evening Social, Fitness Center, Breakfast.The Homewood Suites by Hilton Edgewater-NYC Area, NJ hotel overlooks Manhattan from the western banks of the Hudson River in New Jersey. The convenient location of Homewood Suites by Hilton offers you easy access to all of the Tri-State area's corporate and industrial parks, popular tourist sites and attractions. \n\nThe Homewood Suites by Hilton in Edgewater, New Jersey features 122 spacious studio (king) suites and one-bedroom suites (with a king bed or two queen beds). The EMPIRE Suites boast a Manhattan skyline view and a whirlpool tub overlooking the master bedroom. Our suites will make guests feel right at home and pampered with a fully equipped kitchen including a full-size refrigerator, range top, microwave, dishwasher, and coffeemaker. Each suite has a sofa bed in the living area. Large flat-screen TVs, two-line telephones, iron with ironing board and hairdryers are just a few of the amenities found at our Edgewater, New Jersey Homewood Suites by Hilton hotel.",
    thumbnail:
      'http://photos.hotelbeds.com/giata/16/160156/160156a_hb_f_001.jpg',
    rooms: [
      {
        code: 'SUI.KG',
        room_type: 'SUI',
        description: 'SUITE KING SIZE BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3456.56,
          str: '$3,456.56',
          currency: 'USD',
        },
      },
      {
        code: 'SUI.CV-KG',
        room_type: 'SUI',
        description: 'SUITE CITY VIEW KING BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3604.24,
          str: '$3,604.24',
          currency: 'USD',
        },
      },
      {
        code: 'SUI.KG-3',
        room_type: 'SUI',
        description: 'SUITE KING SIZE BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3308.8,
          str: '$3,308.80',
          currency: 'USD',
        },
      },
    ],
    amount_min: {
      amount: 3308.8,
      str: '$3,308.80',
      currency: 'USD',
    },
    relative_position: {
      distance: 5.9816,
      distance_unit: 'mi',
      near_to: [
        {
          location_type: 'example',
          location_code: '123',
          location_name: 'Example Location',
          distance: '0',
        },
      ],
      distance_to_city_centre: 0.0,
      distance_to_nearest_airport: 0.0,
    },
    address: {
      coordinates: {
        latitude: 40.8065189832902,
        longitude: -73.9901393651826,
        radius: 15,
        unit: 'mi',
      },
      country_code: 'US',
      country: 'United States',
      state: 'NEW JERSEY',
      city: 'Edgewater',
      zone: 'Edgewater',
      district: '',
      address1: '10 The Promenade',
      address2: '',
      postal_code: '',
    },
    type: 'Hotel',
    star_rating: '3',
    web: 'https://www.hilton.com/en/hotels/ewrewhw-homewood-suites-edgewater-nyc-area/',
    email: 'EWREW_Homewood@hilton.com',
    phones: [
      {
        phone_number: '+180022554663',
        phone_type: 'PHONEBOOKING',
      },
    ],
    checkin_time: '14:00:00',
    checkout_time: '10:00:00',
    facilities: [
      'Minor - AvaniSHIELD',
      'Rosen - Total Commitment',
      'Morocco - Tourisme au Maroc post Covid-19',
      'RIU - Covid-19 Health Protocol',
      'Table tennis',
      'Morocco - Tourisme au Maroc post Covid-19',
      'Pedal boating',
      'Extra beds on demand',
      'Breakfast a la carte',
      'Fitness',
      'Cycling / mountain biking',
      'Blue Diamond Resorts - Enhanced Health, Safety & Cleanliness Protocols',
      'Table tennis',
      'Golf',
      'Minimum check-in age',
      'Pedal boating',
      'Wi-fi',
      'Skiing',
      'Squash',
      'Aerobics',
      'Launderette',
      'Multilingual staff',
      'Golf practice facility',
      'Bellboy service',
      'RIU - Covid-19 Health Protocol',
      'NH - Feel safe at NH',
      'Colombia - Check in certificado, COVID-19 bioseguro',
      'Minor - AvaniSHIELD',
      'WTTC - Safe Travels Stamp',
      'Newspapers',
      'Luggage room',
      'Clothes dryer',
      'Diving',
      'Smoking area',
      'Catamaran sailing',
      'Waterskiing',
      'Online check-in',
      'Spa centre',
      'Business centre',
      'Turkish bath (hamam)',
      'WaterSlides',
      'TV lounge',
      'Sauna',
      'Surfing',
      'Hairdressing salon',
      'Mauritian Standard on Sustainable Tourism',
      'Colombia - Check in certificado, COVID-19 bioseguro',
      'Non-smoking establishment',
      'Fitness',
      'Tennis',
      'Hilton - CleanStay',
    ],
    amenities: [],
    chain: {
      chain_code: '',
      chain_name: '',
    },
    supplier_prefix: '704f71db',
    supplier_id: '160156',
  },
  {
    id: '704f71db:160156',
    name: 'Homewood Suites by Hilton Edgewater-NYC Area',
    description:
      "The following services and amenities are available, but with **reduced service**: Complimentary Evening Social, Fitness Center, Breakfast.The Homewood Suites by Hilton Edgewater-NYC Area, NJ hotel overlooks Manhattan from the western banks of the Hudson River in New Jersey. The convenient location of Homewood Suites by Hilton offers you easy access to all of the Tri-State area's corporate and industrial parks, popular tourist sites and attractions. \n\nThe Homewood Suites by Hilton in Edgewater, New Jersey features 122 spacious studio (king) suites and one-bedroom suites (with a king bed or two queen beds). The EMPIRE Suites boast a Manhattan skyline view and a whirlpool tub overlooking the master bedroom. Our suites will make guests feel right at home and pampered with a fully equipped kitchen including a full-size refrigerator, range top, microwave, dishwasher, and coffeemaker. Each suite has a sofa bed in the living area. Large flat-screen TVs, two-line telephones, iron with ironing board and hairdryers are just a few of the amenities found at our Edgewater, New Jersey Homewood Suites by Hilton hotel.",
    thumbnail:
      'http://photos.hotelbeds.com/giata/16/160156/160156a_hb_f_001.jpg',
    rooms: [
      {
        code: 'SUI.KG',
        room_type: 'SUI',
        description: 'SUITE KING SIZE BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3456.56,
          str: '$3,456.56',
          currency: 'USD',
        },
      },
      {
        code: 'SUI.CV-KG',
        room_type: 'SUI',
        description: 'SUITE CITY VIEW KING BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3604.24,
          str: '$3,604.24',
          currency: 'USD',
        },
      },
      {
        code: 'SUI.KG-3',
        room_type: 'SUI',
        description: 'SUITE KING SIZE BED',
        name: 'Bed room',
        capacity: {
          min_pax: 1,
          max_pax: 8,
          min_adults: 1,
          max_adults: 8,
          min_children: 5,
          max_children: 5,
        },
        amount_total: {
          amount: 3308.8,
          str: '$3,308.80',
          currency: 'USD',
        },
      },
    ],
    amount_min: {
      amount: 3308.8,
      str: '$3,308.80',
      currency: 'USD',
    },
    relative_position: {
      distance: 5.9816,
      distance_unit: 'mi',
      near_to: [
        {
          location_type: 'example',
          location_code: '123',
          location_name: 'Example Location',
          distance: '0',
        },
      ],
      distance_to_city_centre: 0.0,
      distance_to_nearest_airport: 0.0,
    },
    address: {
      coordinates: {
        latitude: 40.8065189832902,
        longitude: -73.9901393651826,
        radius: 15,
        unit: 'mi',
      },
      country_code: 'US',
      country: 'United States',
      state: 'NEW JERSEY',
      city: 'Edgewater',
      zone: 'Edgewater',
      district: '',
      address1: '10 The Promenade',
      address2: '',
      postal_code: '',
    },
    type: 'Hotel',
    star_rating: '3',
    web: 'https://www.hilton.com/en/hotels/ewrewhw-homewood-suites-edgewater-nyc-area/',
    email: 'EWREW_Homewood@hilton.com',
    phones: [
      {
        phone_number: '+180022554663',
        phone_type: 'PHONEBOOKING',
      },
    ],
    checkin_time: '14:00:00',
    checkout_time: '10:00:00',
    facilities: [
      'Minor - AvaniSHIELD',
      'Rosen - Total Commitment',
      'Morocco - Tourisme au Maroc post Covid-19',
      'RIU - Covid-19 Health Protocol',
      'Table tennis',
      'Morocco - Tourisme au Maroc post Covid-19',
      'Pedal boating',
      'Extra beds on demand',
      'Breakfast a la carte',
      'Fitness',
      'Cycling / mountain biking',
      'Blue Diamond Resorts - Enhanced Health, Safety & Cleanliness Protocols',
      'Table tennis',
      'Golf',
      'Minimum check-in age',
      'Pedal boating',
      'Wi-fi',
      'Skiing',
      'Squash',
      'Aerobics',
      'Launderette',
      'Multilingual staff',
      'Golf practice facility',
      'Bellboy service',
      'RIU - Covid-19 Health Protocol',
      'NH - Feel safe at NH',
      'Colombia - Check in certificado, COVID-19 bioseguro',
      'Minor - AvaniSHIELD',
      'WTTC - Safe Travels Stamp',
      'Newspapers',
      'Luggage room',
      'Clothes dryer',
      'Diving',
      'Smoking area',
      'Catamaran sailing',
      'Waterskiing',
      'Online check-in',
      'Spa centre',
      'Business centre',
      'Turkish bath (hamam)',
      'WaterSlides',
      'TV lounge',
      'Sauna',
      'Surfing',
      'Hairdressing salon',
      'Mauritian Standard on Sustainable Tourism',
      'Colombia - Check in certificado, COVID-19 bioseguro',
      'Non-smoking establishment',
      'Fitness',
      'Tennis',
      'Hilton - CleanStay',
    ],
    amenities: [],
    chain: {
      chain_code: '',
      chain_name: '',
    },
    supplier_prefix: '704f71db',
    supplier_id: '160156',
  },
] as Hotel[];
